routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('password/change', 'Auth\ChangePasswordController@showChangeForm')->name('password.change');
Route::post('password/change', 'Auth\ChangePasswordController@change');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('test/{test1}/moveto/{test2}', 'HomeController@move')->name('test.move');

// Admin Routes...
Route::get('test/create', 'TestController@showCreateForm')->name('test.create');
Route::get('test/{test}/edit', 'TestController@showEditForm')->name('test.edit');
Route::post('test/create', 'TestController@createForm');
Route::post('test/{test}/edit', 'TestController@editForm');
Route::get('test/{test}/delete', 'TestController@showDeleteForm')->name('test.delete');
Route::post('test/{test}/delete', 'TestController@deleteForm');
Route::get('test/{test}/visibility', 'TestController@showVisibilityForm')->name('test.visibility');
Route::post('test/{test}/visibility/{group}', 'TestController@visibilityForm')->name('test.setvisibility');
Route::post('test/{test}/visibility', 'TestController@visibilityForm')->name('test.changevisibility');
Route::get('test/{test}/clone', 'TestController@clone')->name('test.clone');

Route::get('user/{user}/profile', 'UserController@showProfile')->name('user.profile');
Route::get('user/list', 'UserController@showList')->name('user.list');
Route::get('user/{user}/edit', 'UserController@showEditForm')->name('user.edit');
Route::post('user/{user}/edit', 'UserController@editForm');
Route::get('user/{user}/delete', 'UserController@showDeleteForm')->name('user.delete');
Route::post('user/{user}/delete', 'UserController@deleteUser');
Route::get('user/create', 'UserController@showCreateForm')->name('user.create');
Route::post('user/create', 'UserController@createForm');
Route::get('group/manage', 'GroupController@showManageForm')->name('group.manage');
Route::post('group/create', 'GroupController@createForm')->name('group.create');
Route::post('group/{group}/edit', 'GroupController@editForm')->name('group.edit');
Route::get('group/{group}/delete', 'GroupController@deleteForm')->name('group.delete');
Route::get('user/csv', 'UserController@showFromCSVForm')->name('user.fromcsv');
Route::post('user/csv', 'UserController@createFromCSV');

Route::get('ranking', 'RankingController@show')->name('ranking');

// Test Routes...
Route::get('test/{test}/show', 'DoTestController@showTest')->name('test.show');
Route::post('test/answer/{question}', 'DoTestController@answerQuestion')->name('question.answer');
Route::post('test/hint/{question}', 'DoTestController@hint')->name('question.hint');

Route::get('test/{test}/attempts', 'AttemptsController@showAttemptsForTest')->name('test.attempts');
Route::get('test/{test}/user/{user}/attempts/', 'AttemptsController@showUserAttemptsForTest')->name('testuser.attempts');
Route::get('test/{test}/summary', 'AttemptsController@showSummaryForTest')->name('test.summary');
Route::get('question/{question}/attempts', 'AttemptsController@showAttemptsForQuestion')->name('question.attempts');
Route::get('question/{question}/user/{user}/attempts', 'AttemptsController@showAttemptsForQuestion')->name('user.attempts');
Route::get('question/{question}/reevaluate', 'AttemptsController@showReevaluateForm')->name('question.reevaluate');
Route::post('question/{question}/reevaluate', 'AttemptsController@reevaluate');
Route::get('attempt/{attempt}/delete', 'AttemptsController@delete')->name('attempt.delete');

Route::post('filter/group', 'GroupController@setGroupFilter')->name('filter.group');
Route::get('filter/orderby', 'AttemptsController@setOrderBy')->name('filter.orderby');
Route::get('filter/usersorderby', 'UserController@setOrderBy')->name('filter.usersorderby');

Route::get('category/manage', 'CategoryController@showManageForm')->name('category.manage');
Route::post('category/create', 'CategoryController@createForm')->name('category.create');
Route::post('category/{category}/edit', 'CategoryController@editForm')->name('category.edit');
Route::get('category/{category}/delete', 'CategoryController@deleteForm')->name('category.delete');
Route::get('category/{category1}/moveto/{category2}', 'CategoryController@move')->name('category.move');

Route::post('category/{category}/collapse', 'CategoryController@collapse')->name('category.collapse');
Route::post('category/{category}/expand', 'CategoryController@expand')->name('category.expand');

app/Question.php
<?php

/*
This file is part of QueryTest.

QueryTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Afferi General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

QueryTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Afferi General Public License
along with QueryTest.  If not, see <https://www.gnu.org/licenses/>.
*/

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function test() {
        return $this->belongsTo('App\Test');
    }

    public function attempts() {
        return $this->hasMany('App\Attempt');
    }

    public function isSolved($user) {
        $matchId = Message::where('code', 'MATCH')->first()->id;
        $solved = $this->attempts()->where([
            ['user_id', $user->id],
            ['message_id', $matchId]
        ])->count();
        return $solved>0;
    }

    public function clone() {
        $newquestion = new Question();
        $newquestion->solution = $this->solution;
        $newquestion->question = $this->question;
        $newquestion->hint = $this->hint;
        return $newquestion;
    }
}

app/Http/Controllers/DoTestController.php
<?php

/*
This file is part of QueryTest.

QueryTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Afferi General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

QueryTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Afferi General Public License
along with QueryTest.  If not, see <https://www.gnu.org/licenses/>.
*/

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;
use App\Test;
use App\Question;
use App\Message;
use App\Attempt;
use App\ResultsComparator;
use App\Events\QuestionSolved;
use App\Events\QuestionFailed;
use App\Events\TestSolved;

class DoTestController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', 'test.published']);
        $this->middleware('test.open')->only('answerQuestion');
    }

    private function showResults(Test $test) {
        return view('test.userattempts')->with(['user'=>\Auth::user(), 'test'=>$test]);
    }

    public function showTest(Test $test) {
        if ($test->isClosed(\Auth::user()->group) && $test->areResultsShown(\Auth::user()->group)) {
            return $this->showResults($test);
        }
        $questions = $test->questions()->orderBy('id', 'asc')->withCount([
            'attempts'=>function($query) {
                $query->where('user_id', \Auth::user()->id);
            },
            'attempts as solved'=>function($query) {
                $query->where([
                    ['user_id', \Auth::user()->id],
                    ['message_id', Message::where('code', 'MATCH')->first()->id]
                ]);
            }
        ])->get();
        foreach ($questions as $question) {
            $question->attempts()->where('user_id', \Auth::user()->id);
        }
        return view('test.show')->with('test', $test)->with('questions', $questions);
    }

    private function saveAttempt(Test $test, Question $question, Message $message, $answer) {
        $user = \Auth::user();
        if ($test->areResultsHidden($user->group)) {
            // Save only last attempt
            $question->attempts()->where('user_id', $user->id)->delete();
            Attempt::create($user, $question, $message, $answer);
        } else {
            // Only count attempt if the question is not yet solved
            if (!$question->isSolved($user)) {
                Attempt::create($user, $question, $message, $answer);
                if ($message->code == 'MATCH') {
                    event(new QuestionSolved($user, $question));
                    // Have solved all test questions?
                    $nQuestions = $test->questions()->count();
                    $questionsSolved = $test->nQuestionsSolved($user);
                    if ($nQuestions == $questionsSolved) {
                        event(new TestSolved($user, $test));
                    }
                } else {
                    event(new QuestionFailed($user, $question));
                }
            }
        }
    }

    public function answerQuestion(Request $request, Question $question) {
        $answer = $request->input("answer$question->id");
        $test = $question->test;
        $resultsComparator = new ResultsComparator();
        if (!empty($answer)) {
            try {
                $message = $resultsComparator->checkAnswer($question, $answer);
                if ($test->isPublished(\Auth::user()->group)) {
                    $points = $this->saveAttempt($test, $question, $message, $answer);
                }
                if ($test->areResultsHidden(\Auth::user()->group)) {
                    $message->type='warning';
                    $message->message='Attempt saved.';
                }
            } catch (QueryException $e) {
                $request->session()->flash('status', "Error in question $question->id official answer: ".$e->getMessage());
                return redirect('home');
            }
        } else {
            $message = new Message();
            $message->type='error';
            $message->message='Empty answer.';
        }
        return redirect("test/$test->id/show#question$question->id")->with(['questionid'=>$question->id, 'message'=>$message])->withInput();
    }

    public function hint(Request $request, Question $question) {
        $message = Message::where('code', 'HINT')->firstOrFail();
        $n_attempts = $question->attempts()->where('user_id', \Auth::user()->id)->count();
        $n_hints = $question->attempts()->where('user_id', \Auth::user()->id)->where('message_id', $message->id)->count();
        $result = '';
        if ($n_attempts > 0) {
          if ($n_hints == 0) {
            $this->saveAttempt($question->test, $question, $message, '');
          }
          $result = $question->hint;
        }
        return $result;
    }
}

resources/views/question/answer_form.blade.php
<form class="form-horizontal" method="POST" action="{{ route('question.answer', ['question' => $question->id]) }}">
    {{ csrf_field() }}
    <div class="row form-group{{ session('questionid')===$question->id ? ' has-'.session('message')->type : '' }}">
        <label for="answer{{ $question->id }}" class="col-md-2 col-form-label text-right">Your answer</label>
        <div class="col-md-8">
            <textarea id="answer{{ $question->id }}" class="form-control" name="answer{{ $question->id }}"
                cols="60" rows="5">{{ old('answer'.$question->id) }}</textarea>
            @if (session('questionid')===$question->id)
                <span class="help-block">
                    <strong>{{ session('message')->message }}  </strong>
                    @if (session('questionPoints')!=0)
                        <strong>You win {{ session('questionPoints') }} points!</strong>
                    @endif
                    @if (session('testPoints')!=0)
                        <strong>You win {{ session('testPoints') }} points for completing the whole test!!</strong>
                    @endif
                </span>
            @endif
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-1 offset-md-2">
            <button type="submit" class="btn btn-primary">
                Send
            </button>
        </div>
        <div class="col-md-5">
            @if ($test->areResultsShown(Auth::user()->group)==true)
              @if ($question->attempts_count==0)
                Not yet tried.
              @elseif ($question->solved>0)
                @if ($question->attempts_count==1)
                  <span class="text-success">Solved at the first try!</span>
                @else
                  <span class="text-success">Already solved (using {{ $question->attempts_count }} attempt{{ $question->attempts_count==1?'':'s' }}).</span>
                @endif
              @else
                @if ($question->hint!='')
                  <button class="btn btn-secondary hint-btn" type="button" id="hint-btn-{{ $question->id }}">Show hint</button>
                @endif
                <span class="text-warning">Tried {{ $question->attempts_count }} time{{ $question->attempts_count==1?'':'s' }}.</span>
              @endif
            @else
              @if ($question->attempts_count==0)
                Not yet answered.
              @else
                <span class="text-info">Already answered.</span>
              @endif
            @endif
        </div>
        <div class="col-md-2 text-right">
        @if (Auth::user()->hasRole('Teacher'))
            <a class="btn btn-secondary" href="{{ route('question.reevaluate', ['question' => $question->id]) }}" data-toggle="tooltip" title="Reevaluate">
                <svg class="feather text-white" aria-hidden="true" aria-label="Reevaluate">
                    <use xlink:href="{{ asset('images/feather-sprite.svg#refresh-cw') }}"/>
                </svg>
            </a>
            <a class="btn btn-secondary" href="{{ route('question.attempts', ['question' => $question->id]) }}" data-toggle="tooltip" title="View attempts">
                <svg class="feather text-white" aria-hidden="true" aria-label="View attempts">
                    <use xlink:href="{{ asset('images/feather-sprite.svg#zoom-in') }}"/>
                </svg>
            </a>
        @else
            <a class="btn btn-secondary" href="{{ route('user.attempts', ['user' => Auth::user()->id, 'question' => $question->id]) }}"  data-toggle="tooltip" title="View attempts">
                <svg class="feather text-white" aria-hidden="true" aria-label="View attempts">
                    <use xlink:href="{{ asset('images/feather-sprite.svg#zoom-in') }}"/>
                </svg>
            </a>
        @endif
        </div>
    </div>
    <div class="row" id="hint-text-{{ $question->id }}" style="display:none">
      <div class="col-md-8 offset-md-2"><span class="font-weight-bold"></span></div>
    </div>
</form>

resources/views/question/reevaluate.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include ('test.header_panel')
    <div class="row"><div class="col-md-12"><div class="card border-danger">
        <div class="card-header text-white bg-danger">Reevaluate question</div>
        <div class="card-body">
            <div class="row"><div class="col-md-12">
                <p>This will reevaluate ALL attempts to this question. No points will be rewarded or substracted from users.</p>
                <p>There are {{ $n_attempts }} attempts to this question, from which {{ $modified }} will be modified.</p>
                <form class="form-horizontal" method="POST" action="{{ route('question.reevaluate', ['question' => $question->id]) }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <div class="col-md-2 offset-md-5">
                            <button type="submit" class="btn btn-danger btn-block">
                                Confirm
                            </button>
                        </div>
                    </div>
                </form>
            </div></div>
        </div>
    </div></div></div>
</div>
@endsection

resources/views/question/show_answer.blade.php
@if ($test->areResultsShown(Auth::user()->group) || Auth::user()->hasRole('Teacher'))
  <div class="row"><div class="col-md-offset-2 col-md-8">
    Solution: <br>
    {!! Markdown::convertToHtml("```sql\n".$question->solution."\n```") !!}
  </div></div>
@endif
<div class="row"><div class="col-md-offset-2 col-md-6">
  @if ($test->areResultsShown(Auth::user()->group))
    @if ($question->attempts_count==0)
      You haven't answered this question.
    @elseif ($question->solved>0)
      <span class="text-success">You solved this question!</span>
    @else
      <span class="text-warning">You didn't solved this question.</span>
    @endif
  @else
    @if ($question->attempts_count==0)
      You didn't answer this question.
    @else
      <span class="text-info">You answered this question.</span>
    @endif
  @endif
</div>
<div class="col-md-2 text-right">
  @if (Auth::user()->hasRole('Teacher'))
    <a class="btn btn-secondary" href="{{ route('question.reevaluate', ['question' => $question->id]) }}" data-toggle="tooltip" title="Reevaluate">
        <svg class="feather text-white" aria-hidden="true" aria-label="View attempts">
            <use xlink:href="{{ asset('images/feather-sprite.svg#refresh-cw') }}"/>
        </svg>
    </a>
    <a class="btn btn-default" href="{{ route('question.attempts', ['question' => $question->id]) }}" data-toggle="tooltip" title="View attempts">
        <svg class="feather text-white" aria-hidden="true" aria-label="View attempts">
            <use xlink:href="{{ asset('images/feather-sprite.svg#zoom-in') }}"/>
        </svg>
    </a>
  @else
    <a class="btn btn-default" href="{{ route('user.attempts', ['user' => Auth::user()->id, 'question' => $question->id]) }}" data-toggle="tooltip" title="View attempts">
        <svg class="feather text-white" aria-hidden="true" aria-label="View attempts">
            <use xlink:href="{{ asset('images/feather-sprite.svg#zoom-in') }}"/>
        </svg>
    </a>
  @endif
</div></div>